### ISSUE TITLE
Compact main menu

### ISSUE THREAD

**Issue by tkashkin** [tkashkin/Adwaita-for-Steam#179]
Figure out if it's possible to make the main Steam menu more Adwaita-like. Ideally it should be a single icon button.

**Comment by tkashkin** [comment]
@Foldex any ideas?

Maybe we can expand the original menu on `:hover` or `:focus`.
We'll probably have to also somehow patch Steam's JS code to do anything more complicated.

It should be possible to do with CSS if there's a way to edit the menu to only have one submenu like the VGUI menu had.

**Comment by Foldex** [comment]
I had played with it before, but there's some gotchas involved due to how headerbar menus are implemented. The popover menus spawned by clicking a nav/root menu are actually their own, separate windows.

```css

.rootmenu_RootMenuBar_1Ky59.steamdesktop_RootMenuBar_3s0lk > .rootmenu_RootMenuButton_2UyOB:not(:first-child) {
	display: none !important;
}

.rootmenu_RootMenuBar_1Ky59.steamdesktop_RootMenuBar_3s0lk:hover > .rootmenu_RootMenuButton_2UyOB:not(:first-child) {
	display: block !important;
}
```

Will work, but when you `:hover` over the spawned menu,  you go back to hiding the root menu. 

It obviously looks strange having the menu drop down from an element that is no longer visible. 

Neither `:focus` nor `:focus-within` seem to apply here either.

![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/73fc9fb2-ecce-4990-8247-189b8c76372a)
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/14c98b60-0ee4-40f0-9d08-7d90a0338a0b)
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/c261938b-5fda-4b1a-9782-8f9d5bd73408)
