### ISSUE TITLE
Custom css not working anymore 

### ISSUE THREAD

**Issue by Chrispycode** [tkashkin/Adwaita-for-Steam#283]
I tried v3.0 and now my custom css won't work anymore , I tried uninstalling and reinstalling but it does not work anymore.

I used this command 

```bash
./install.py -e windowcontrols/left --custom-css
```

And that's my custom css

```css
:root {
	/* The main accent color and the matching text value */
	--adw-accent-bg-rgb: 0, 0, 0;
	--adw-accent-fg-rgb: 255, 255, 255;
	--adw-accent-rgb: 150, 0, 0;

	/* destructive-action buttons */
	--adw-destructive-bg-rgb: 0, 0, 0;
	--adw-destructive-fg-rgb: 255, 255, 255;
	--adw-destructive-rgb: 255, 123, 99;

	/* Levelbars, entries, labels and infobars. These don't need text colors */
	--adw-success-bg-rgb: 38, 162, 105;
	--adw-success-fg-rgb: 255, 255, 255;
	--adw-success-rgb: 143, 240, 164;

	--adw-warning-bg-rgb: 205, 147, 9;
	--adw-warning-fg-rgb: 0, 0, 0;
	--adw-warning-fg-a: 0.8;
	--adw-warning-rgb: 248, 228, 92;

	--adw-error-bg-rgb: 0, 0, 0;
	--adw-error-fg-rgb: 255, 255, 255;
	--adw-error-rgb: 255, 123, 99;

	/* Window */
	--adw-window-bg-rgb: 0, 0, 0;
	--adw-window-fg-rgb: 255, 255, 255;

	/* Views - e.g. text view or tree view */
	--adw-view-bg-rgb: 0, 0, 0;
	--adw-view-fg-rgb: 255, 255, 255;

	/* Header bar, search bar, tab bar */
	--adw-headerbar-bg-rgb: 0, 0, 0;
	--adw-headerbar-fg-rgb: 255, 255, 255;
	--adw-headerbar-border-rgb: 255, 255, 255;
	--adw-headerbar-backdrop-rgb: var(--adw-window-bg-rgb);
	--adw-headerbar-shade-rgb: 0, 0, 0;
	--adw-headerbar-shade-a: 0.36;
	--adw-headerbar-darker-shade-rgb: 0, 0, 0;
	--adw-headerbar-darker-shade-a: 0.9;

	/* Split pane views */
	--adw-sidebar-bg-rgb: 0, 0, 0;
	--adw-sidebar-fg-rgb: 255, 255, 255;
	--adw-sidebar-backdrop-rgb: 42, 42, 42;
	--adw-sidebar-shade-rgb: 0, 0, 0;
	--adw-sidebar-shade-a: 0.36;

	--adw-secondary-sidebar-bg-rgb: 0, 0, 0;
	--adw-secondary-sidebar-fg-rgb: 255, 255, 255;
	--adw-secondary-sidebar-backdrop-rgb: 39, 39, 39;
	--adw-secondary-sidebar-shade-rgb: 0, 0, 0;
	--adw-secondary-sidebar-shade-a: 0.36;

	/* Cards, boxed lists */
	--adw-card-bg-rgb: 255, 255, 255;
	--adw-card-bg-a: 0.08;
	--adw-card-fg-rgb: 255, 255, 255;
	--adw-card-shade-rgb: 0, 0, 0;
	--adw-card-shade-a: 0.36;

	/* Dialogs */
	--adw-dialog-bg-rgb: 0, 0, 0;
	--adw-dialog-fg-rgb: 255, 255, 255;

	/* Popovers */
	--adw-popover-bg-rgb: 0, 0, 0;
	--adw-popover-fg-rgb: 255, 255, 255;
	--adw-popover-shade-rgb: 0, 0, 0;
	--adw-popover-shade-a: 0.36;

	/* Thumbnails */
	--adw-thumbnail-bg-rgb: 0, 0, 0;
	--adw-thumbnail-fg-rgb: 255, 255, 255;

	/* Miscellaneous */
	--adw-shade-rgb: 0, 0, 0;
	--adw-shade-a: 0.36;
}
```
