### ISSUE TITLE
Webkit Theming

### ISSUE THREAD

**Issue by Foldex** [tkashkin/Adwaita-for-Steam#3]
>New library, new chat, other web-based client parts: not skinnable without third-party tools

Not sure if this would be in scope (hence no PR), but I did want to mention that the linux version of the steam client differs from the windows client in this regard.

You can actually theme some web bits by making use of `resource/webkit.css`. Here's an example that changes the New Library's background and hides the "What's New" Shelf, which normally can't be completely disabled.

```css
:root {
    --bg: #242424;
    --fg: #ffffff;
    --shade_color: rgba(0, 0, 0, 0.36);

    --accent: #78aeed;
    --accent_bg_color: #3584e4;
    --accent_fg_color: var(--fg);

    --destructive_color: #ff7b63;
    --destructive_bg_color: #c01c28;
    --destructive_fg_color: var(--fg);

    --success_color: #8ff0a4;
    --success_bg_color: #26a269;
    --success_fg_color: var(--fg);

    --warning_color: #f8e45c;
    --warning_bg_color: #cd9309;
    --warning_fg_color: var(--fg);

    --error_color: #ff7b63;
    --error_bg_color: #c01c28;
    --error_fg_color: var(--fg);

    --window_bg_color: var(--bg);
    --window_fg_color: var(--fg);

    --view_bg_color: #1e1e1e;
    --view_fg_color: var(--fg);

    --headerbar_bg_color: #303030;
    --headerbar_fb_color: var(--fg);
    --headerbar_border_color: var(--fg);
    --headerbar_backdrop_color: var(--bg);
    --headerbar_shade_color: var(--shade_color);

    --popover_bg_color: #383838;
    --popover_fg_color: var(--fg);
}

/* Library Background */
[class*="gamelistbar_Container"],
[class*="libraryhome_LibraryHome"] {
    background: var(--bg) !important;
}

/* Library Left Panel Section Headers */
[class*="gamelistsectionheader_Container"] {
    background: var(--view_bg_color) !important;
}

/* Hide What's New Shelf */
[class*="libraryhome_UpdatesContainer"],
[class*="libraryhomeshowcases_AddShowcaseRow"] {
    display: none !important;
}

```
